<?php
// $Id$

/**
 * @file
 *   Views content cache cache.
 */

/**
 * Implementation of hook_views_api().
 */
function views_content_cache_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'views_content_cache') .'/views',
  );
}

/**
 * Get the last update time for a given content type.
 */
function views_content_cache_last_update_get($type) {
  return variable_get('views_content_cache_last_update_' . $type, 0);
}

/**
 * Set the last update time for a given content type.
 */
function views_content_cache_last_update_set($type, $time = NULL) {
  if (is_null($time)) {
    $time = time();
  }
  variable_set('views_content_cache_last_update_' . $type, $time);
}

/**
 * Implementation of hook_nodeapi().
 *
 * Detect changes to node types and record the modification time.
 */
function views_content_cache_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'insert':
    case 'update':
    case 'delete':
    case 'delete revision':
      views_content_cache_last_update_set($node->type);
      break;
  }
}

/**
 * Implementation of hook_comment().
 */
function views_comment_cache_comment(&$a1, $op) {
  return;
  switch ($op) {
    case 'insert':
    case 'update':
    case 'delete':
    case 'publish':
    case 'unpublish':
      if (!empty($a1['nid'])) {
        if ($node =  node_load($a1['nid'])) {
          views_content_cache_last_update_set($node->type);
        }
      }
      break;
  }
}
